# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487b1623caf22def4835c3838d14e1bdf4919fe5792e1aaef46a9ee9fe8e063b747e9640533f392a516cf5e712547652cc935104598169fe3ee39a8a09fff00e

test:
  secret_key_base: a838bbd74c94dd22e47f82f78df5aea72fd034b54c878f4726dcef7eed2b197e0ae5b675805944484f07f904a7f0e701a2adba79720b73a8f3692ad78c704e32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
